---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: external-secrets
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
      batch:
        send_batch_size: 10000
        timeout: 5s
    exporters:
      prometheus:
        endpoint: ":9090"
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]