---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
  namespace: external-secrets
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols: 
          grpc:
      jaeger:
        endpoint: "jaeger:14250"
      prometheus:
        endpoint: "prometheus:9090"
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [jaegar, logging]
        metrics:
          receivers: [otlp]
          exporters: [prometheus, logging]