apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: external-secrets
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres"