apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: external-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== # mypassword (base64 encoded)
  POSTGRES_DB: dHJhbnNhY3Rpb25z # transactions (base64 encoded)
