apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: external-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==
  POSTGRES_DB: dHJhbnNhY3Rpb25z
