name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: "public.ecr.aws/c0v8s4a9"
        ECR_REPOSITORY: "transactionapi"
        IMAGE_TAG: latest
      run: |
        #docker login
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c0v8s4a9

        # Build the Docker image
        docker build "app" -f "app/Dockerfile" -t $ECR_REPOSITORY:$IMAGE_TAG

        # Tag the image for ECR
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        # Push the image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG



    - name: "Install Kubectl"
      uses: marcofranssen/setup-kubectl@v0.3.0
      with:
          kubectl-version: latest


    - name: Update kube config
      run: aws eks update-kubeconfig --name external-secrets --region us-west-2

    - name: "Deploy to EKS"
      run : kubectl apply -f K8s/app-deployment.yml
