name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Terraform Init
      working-directory: ../terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ../terraform
      run: terraform plan -out=plan.tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ../terraform
      run: terraform apply -auto-approve plan.tfplan
